name: 'enterprise_pji'
version: '1.0.0'
config-version: 2
profile: 'enterprise_pji'

model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  enterprise_pji:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
