import os
import duckdb
import pandas as pd
import streamlit as st

def query_df(sql: str) -> pd.DataFrame:
    # Inside container, this connects directly to the shared local duckdb file
    # generated by dbt transformation flow
    db_path = "/data/duckdb/pji_analytics.duckdb"
    
    # Open connection in read-only mode and release lock immediately using a context manager
    with duckdb.connect(db_path, read_only=True) as con:
        return con.execute(sql).fetchdf()
