import os
import duckdb
import pandas as pd
import streamlit as st

@st.cache_resource
def get_connection():
    # Inside container, this connects directly to the shared local duckdb file
    # generated by dbt transformation flow
    db_path = "/tmp/pji_analytics.duckdb"
    
    con = duckdb.connect(db_path, read_only=True)
    return con

def query_df(sql: str) -> pd.DataFrame:
    con = get_connection()
    return con.execute(sql).fetchdf()
