[sources.sql_database.credentials]
drivername = "postgresql"
database = "erp_db"
password = "erp_password_2024"
username = "erp_user"
host = "postgres"
port = 5432

[destination.filesystem.credentials]
aws_access_key_id = "minioadmin"
aws_secret_access_key = "minioadmin"
endpoint_url = "http://minio:9000"

